export const freelancers = [
  {
    id: 1,
    name: "Ada Chen",
    title: "Full-Stack Developer",
    category: "Development",
    location: "Singapore",
    trustScore: 98,
    rating: 4.9,
    jobs: 187,
    rate: 95,
    badge: "TOP RATED",
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL"],
  },

  {
    id: 2,
    name: "Marco Rivera",
    title: "Brand & Visual Designer",
    category: "Design",
    location: "Barcelona, Spain",
    trustScore: 94,
    rating: 4.8,
    jobs: 121,
    rate: 75,
    badge: "VERIFIED PRO",
    skills: ["Figma", "Branding", "UI/UX"],
  },

  {
    id: 3,
    name: "Priya Nair",
    title: "Mobile App Developer",
    category: "Development",
    location: "Mumbai, India",
    trustScore: 91,
    rating: 4.7,
    jobs: 63,
    rate: 85,
    badge: "RISING TALENT",
    skills: ["Flutter", "React Native", "Swift"],
  },

  {
    id: 4,
    name: "David Kwame",
    title: "Data Scientist",
    category: "Data & AI",
    location: "Accra, Ghana",
    trustScore: 96,
    rating: 4.9,
    jobs: 62,
    rate: 120,
    badge: "TOP RATED",
    skills: ["Python", "TensorFlow", "SQL"],
  },

  {
    id: 5,
    name: "Sofia Rossi",
    title: "UI/UX Designer",
    category: "Design",
    location: "Milan, Italy",
    trustScore: 93,
    rating: 4.8,
    jobs: 134,
    rate: 80,
    badge: "VERIFIED PRO",
    skills: ["Figma", "Design Systems"],
  },

  {
    id: 6,
    name: "Nina Okafor",
    title: "Technical Writer",
    category: "Writing",
    location: "London, UK",
    trustScore: 92,
    rating: 4.9,
    jobs: 79,
    rate: 50,
    badge: "AVAILABLE",
    skills: ["Technical Writing", "API Docs"],
  },
];