export const projects = [
  {
    id: 1,
    title: "E-Commerce Platform Rebuild",
    description:
      "Full rewrite of the storefront using React and headless CMS architecture.",
    status: "Active",
    category: "Development",
    budget: 12000,
    spent: 7000,
    progress: 65,
    deadline: "Jul 15, 2026",
    freelancer: "David Kwame",
    rating: 4.9,
    completedMilestones: 3,
    totalMilestones: 4,
    milestones: [
      { title: "Requirements Gathering", completed: true },
      { title: "UI Design", completed: true },
      { title: "Frontend Development", completed: true },
      { title: "Deployment", completed: false },
    ],
  },

  {
    id: 2,
    title: "Brand Identity & Logo Design",
    description:
      "Complete visual identity system including logo, typography, and brand guidelines.",
    status: "Review",
    category: "Design",
    budget: 3500,
    spent: 3000,
    progress: 90,
    deadline: "Jun 20, 2026",
    freelancer: "Marco Rivera",
    rating: 4.8,
    completedMilestones: 3,
    totalMilestones: 4,
    milestones: [
      { title: "Research", completed: true },
      { title: "Logo Concepts", completed: true },
      { title: "Brand Guide", completed: true },
      { title: "Final Approval", completed: false },
    ],
  },

  {
    id: 3,
    title: "Mobile App MVP",
    description:
      "Cross-platform mobile app with authentication, payments, and notifications.",
    status: "Active",
    category: "Development",
    budget: 22000,
    spent: 9000,
    progress: 42,
    deadline: "Sep 1, 2026",
    freelancer: "Priya Nair",
    rating: 4.7,
    completedMilestones: 2,
    totalMilestones: 5,
    milestones: [
      { title: "Planning", completed: true },
      { title: "UI Wireframes", completed: true },
      { title: "Backend APIs", completed: false },
      { title: "Testing", completed: false },
      { title: "Launch", completed: false },
    ],
  },

  {
    id: 4,
    title: "SEO & Content Strategy",
    description:
      "SEO audit, keyword research, and content roadmap for six months.",
    status: "Open",
    category: "Marketing",
    budget: 4000,
    spent: 0,
    progress: 0,
    deadline: "Aug 30, 2026",
    freelancer: "Not Assigned",
    rating: 0,
    completedMilestones: 0,
    totalMilestones: 4,
    milestones: [
      { title: "Audit", completed: false },
      { title: "Keyword Research", completed: false },
      { title: "Content Plan", completed: false },
      { title: "Implementation", completed: false },
    ],
  },

  {
    id: 5,
    title: "Backend API Integration",
    description:
      "Third-party payment gateway and logistics provider integrations.",
    status: "Completed",
    category: "Development",
    budget: 8500,
    spent: 8500,
    progress: 100,
    deadline: "May 1, 2026",
    freelancer: "Sam Osei",
    rating: 4.9,
    completedMilestones: 4,
    totalMilestones: 4,
    milestones: [
      { title: "API Design", completed: true },
      { title: "Core Endpoints", completed: true },
      { title: "Integrations", completed: true },
      { title: "Documentation", completed: true },
    ],
  },

  {
    id: 6,
    title: "Data Dashboard & Analytics",
    description:
      "Analytics dashboard visualizing KPIs, retention, and revenue metrics.",
    status: "Paused",
    category: "Data & AI",
    budget: 9000,
    spent: 2700,
    progress: 30,
    deadline: "Oct 10, 2026",
    freelancer: "David Kwame",
    rating: 4.9,
    completedMilestones: 1,
    totalMilestones: 4,
    milestones: [
      { title: "Requirements", completed: true },
      { title: "Data Pipeline", completed: false },
      { title: "Dashboard UI", completed: false },
      { title: "Deployment", completed: false },
    ],
  },

  {
    id: 7,
    title: "AI Chatbot Assistant",
    description:
      "Customer support chatbot powered by GPT APIs and custom workflows.",
    status: "Active",
    category: "Data & AI",
    budget: 15000,
    spent: 5000,
    progress: 35,
    deadline: "Nov 15, 2026",
    freelancer: "Yuki Tanaka",
    rating: 4.8,
    completedMilestones: 2,
    totalMilestones: 6,
    milestones: [
      { title: "Requirements", completed: true },
      { title: "Conversation Design", completed: true },
      { title: "API Setup", completed: false },
      { title: "Training", completed: false },
      { title: "Testing", completed: false },
      { title: "Launch", completed: false },
    ],
  },

  {
    id: 8,
    title: "Technical Blog Writing",
    description:
      "Creation of long-form technical content and product documentation.",
    status: "Review",
    category: "Writing",
    budget: 2500,
    spent: 2200,
    progress: 88,
    deadline: "Jun 25, 2026",
    freelancer: "Nina Okafor",
    rating: 4.9,
    completedMilestones: 3,
    totalMilestones: 4,
    milestones: [
      { title: "Research", completed: true },
      { title: "Draft", completed: true },
      { title: "Review", completed: true },
      { title: "Publication", completed: false },
    ],
  },

  {
    id: 9,
    title: "Product Demo Video",
    description:
      "Professional animated explainer video for product marketing.",
    status: "Active",
    category: "Marketing",
    budget: 6000,
    spent: 2500,
    progress: 45,
    deadline: "Jul 30, 2026",
    freelancer: "Sofia Rossi",
    rating: 4.8,
    completedMilestones: 2,
    totalMilestones: 5,
    milestones: [
      { title: "Script", completed: true },
      { title: "Storyboard", completed: true },
      { title: "Animation", completed: false },
      { title: "Voiceover", completed: false },
      { title: "Delivery", completed: false },
    ],
  },

  {
    id: 10,
    title: "Cloud Infrastructure Setup",
    description:
      "AWS deployment, CI/CD pipelines, monitoring, and backups.",
    status: "Completed",
    category: "Development",
    budget: 11000,
    spent: 11000,
    progress: 100,
    deadline: "Apr 10, 2026",
    freelancer: "Akash Patel",
    rating: 4.9,
    completedMilestones: 5,
    totalMilestones: 5,
    milestones: [
      { title: "Architecture", completed: true },
      { title: "AWS Setup", completed: true },
      { title: "CI/CD", completed: true },
      { title: "Monitoring", completed: true },
      { title: "Documentation", completed: true },
    ],
  },
];